---
# tasks file for java
- name: install software (rpm/dpkg)
  package:
    name: "{{ item }}"
  with_items:
    - "{{ java_packages[ansible_distribution][java_vendor][java_type][java_version]['name'] }}"
  when:
    - java_vendor == "openjdk"

- name: ensure directory exist
  file:
    path: /opt/{{ java_type }}
    state: directory
  when:
    - java_vendor == "oracle"

- name: install software (tar.gz)
  unarchive:
    src: "{{ item }}"
    dest: "{{ java_install_directory }}/{{ java_type }}"
  with_items:
    - "{{ java_packages[java_vendor][java_type][java_version]['name'] }}"
  when:
    - java_vendor == "oracle"

- name: set alternative (tar.gz)
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java_install_directory }}/{{ java_type }}/{{ java_packages[java_vendor][java_type][java_version]['directory'] }}/bin/java"
  when:
    - java_vendor == "oracle"
