---
# tasks file for java
- name: install software (package)
  package:
    name: "{{ item }}"
  with_items:
    - "{{ java_package[ansible_distribution][ansible_distribution_major_version][java_vendor][java_type][java_version]['name'] }}"
  when:
    - java_vendor == "openjdk"

- name: copy software (rpm)
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - "{{ java_package[java_vendor][java_type][java_version]['rpm'] }}"
  when:
    - java_vendor == "oracle"
    - java_format == "rpm"

- name: install software (rpm)
  package:
    name: "{{ item }}"
  with_items:
    - "/tmp/{{ java_package[java_vendor][java_type][java_version]['rpm'] }}"
  when:
    - java_vendor == "oracle"
    - java_format == "rpm"

- name: ensure java_install_directory exists
  file:
    path: "{{ java_install_directory }}"
    state: directory
  when:
    - java_vendor == "oracle"
    - java_format == "targz"

- name: install software (targz)
  unarchive:
    src: "{{ item }}"
    dest: "{{ java_install_directory }}"
  with_items:
    - "{{ java_package[java_vendor][java_type][java_version]['targz'] }}"
  when:
    - java_vendor == "oracle"
    - java_format == "targz"

- name: install policy software (targz)
  unarchive:
    src: jce_policy-8.zip
    dest: "{{ java_install_directory }}"
  with_items:
    - "{{ java_package[java_vendor][java_type][java_version]['targz'] }}"
  when:
    - java_jce is defined
    - java_vendor == "oracle"
    - java_version == 8

- name: set alternative (targz)
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java_install_directory }}/{{ java_package[java_vendor][java_type][java_version]['directory'] }}/bin/java"
  when:
    - java_vendor == "oracle"
    - java_format == " targz"
