---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-6-default
    image: centos:6
  - name: centos-6-openjdk-6-jre
    image: centos:6
  - name: centos-6-openjdk-6-jdk
    image: centos:6
  - name: centos-6-openjdk-7-jre
    image: centos:6
  - name: centos-6-openjdk-7-jdk
    image: centos:6
  - name: centos-6-openjdk-8-jre
    image: centos:6
  - name: centos-6-openjdk-8-jdk
    image: centos:6
  - name: centos-7-default
    image: centos:7
  - name: centos-7-openjdk-6-jre
    image: centos:7
  - name: centos-7-openjdk-6-jdk
    image: centos:7
  - name: centos-7-openjdk-7-jre
    image: centos:7
  - name: centos-7-openjdk-7-jdk
    image: centos:7
  - name: centos-7-openjdk-8-jre
    image: centos:7
  - name: centos-7-openjdk-8-jdk
    image: centos:7
  - name: centos-6-oracle-8-jre
    image: centos:6
  - name: centos-6-oracle-8-jdk
    image: centos:6
  - name: centos-6-oracle-9-jre
    image: centos:6
  - name: centos-6-oracle-9-jdk
    image: centos:6
  - name: centos-7-oracle-8-jre
    image: centos:7
  - name: centos-7-oracle-8-jdk
    image: centos:7
  - name: centos-7-oracle-9-jre
    image: centos:7
  - name: centos-7-oracle-9-jdk
    image: centos:7
  - name: debian-jessie-default
    image: debian:jessie
  - name: debian-jessie-openjdk-7-jre
    image: debian:jessie
  - name: debian-jessie-openjdk-7-jdk
    image: debian:jessie
  - name: debian-buster-openjdk-8-jre
    image: debian:buster
  - name: debian-buster-openjdk-8-jdk
    image: debian:buster
  - name: debian-jessie-oracle-8-jre
    image: debian:jessie
  - name: debian-jessie-oracle-8-jdk
    image: debian:jessie
  - name: debian-jessie-oracle-9-jre
    image: debian:jessie
  - name: debian-jessie-oracle-9-jdk
    image: debian:jessie
  - name: debian-buster-oracle-8-jre
    image: debian:buster
  - name: debian-buster-oracle-8-jdk
    image: debian:buster
  - name: debian-buster-oracle-9-jre
    image: debian:buster
  - name: debian-buster-oracle-9-jdk
    image: debian:buster
  # Fedora 26 OpenJDK
  - name: fedora-26-default
    image: fedora:26
  - name: fedora-26-openjdk-6-jre
    image: fedora:26
  - name: fedora-26-openjdk-6-jdk
    image: fedora:26
  - name: fedora-26-openjdk-7-jre
    image: fedora:26
  - name: fedora-26-openjdk-7-jdk
    image: fedora:26
  - name: fedora-26-openjdk-8-jre
    image: fedora:26
  - name: fedora-26-openjdk-8-jdk
    image: fedora:26
  # Fedora 27 OpenJDK
  - name: fedora-27-default
    image: fedora:27
  - name: fedora-27-openjdk-6-jre
    image: fedora:27
  - name: fedora-27-openjdk-6-jdk
    image: fedora:27
  - name: fedora-27-openjdk-7-jre
    image: fedora:27
  - name: fedora-27-openjdk-7-jdk
    image: fedora:27
  - name: fedora-27-openjdk-8-jre
    image: fedora:27
  - name: fedora-27-openjdk-8-jdk
    image: fedora:27
  # Fedora 26 oracle
  - name: fedora-26-oracle-8-jre
    image: fedora:26
  - name: fedora-26-oracle-8-jdk
    image: fedora:26
  - name: fedora-26-oracle-9-jre
    image: fedora:26
  - name: fedora-26-oracle-9-jdk
    image: fedora:26
  # Fedora 27 oracle
  - name: fedora-27-oracle-8-jre
    image: fedora:27
  - name: fedora-27-oracle-8-jdk
    image: fedora:27
  - name: fedora-27-oracle-9-jre
    image: fedora:27
  - name: fedora-27-oracle-9-jdk
    image: fedora:27

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: 'None'
