---
- name: install openjdk 6 jre
  hosts: "*-openjdk-6-jre"
  gather_facts: no
  become: yes
  strategy: free

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 6

- name: install openjdk 7 jre
  hosts: "*-openjdk-7-jre"
  gather_facts: no
  become: yes
  strategy: free

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 7

- name: install openjdk 8 jre
  hosts: "*-openjdk-8-jre"
  gather_facts: no
  become: yes
  strategy: free

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 8

- name: install openjdk 9 jre
  hosts: "*-openjdk-9-jre"
  gather_facts: no
  become: yes
  strategy: free

  roles:
    - role: ansible-role-java
      java_vendor: openjdk
      java_version: 9
