---
### CentOS 6 openjdk
- name: install centos 6 default (openjdk, 7)
  hosts: centos-6-default
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java

- name: install centos 6 openjdk 6 jre
  hosts: centos-6-openjdk-6-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 6

- name: install centos 6 openjdk 6 jdk
  hosts: centos-6-openjdk-6-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 6
      java_jdk: yes

- name: install centos 6 openjdk 7 jre
  hosts: centos-6-openjdk-7-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 7

- name: install centos 6 openjdk 7 jdk
  hosts: centos-6-openjdk-7-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 7
      java_jdk: yes

- name: install centos 6 openjdk 8 jre
  hosts: centos-6-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 8

- name: install centos 6 openjdk 8 jdk
  hosts: centos-6-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 8
      java_jdk: yes

### CentOS 7 openjdk
- name: install centos 7 default (openjdk, 7)
  hosts: centos-7-default
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java

- name: install centos 7 openjdk 6 jre
  hosts: centos-7-openjdk-6-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 6

- name: install centos 7 openjdk 6 jdk
  hosts: centos-7-openjdk-6-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 6
      java_jdk: yes

- name: install centos 7 openjdk 7 jre
  hosts: centos-7-openjdk-7-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 7

- name: install centos 7 openjdk 7 jdk
  hosts: centos-7-openjdk-7-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 7
      java_jdk: yes

- name: install centos 7 openjdk 8 jre
  hosts: centos-7-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_version: 8
      java_jdk: yes

- name: install centos 7 openjdk 8 jdk
  hosts: centos-7-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 8
      java_jdk: yes

### Debian Jessie openjkd
- name: install debian jessie default (openjdk, 7)
  hosts: debian-jessie-default
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java

- name: install debian jessie openjdk 7 jre
  hosts: debian-jessie-openjdk-7-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 7

- name: install debian jessie openjdk 7 jdk
  hosts: debian-jessie-openjdk-7-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 7
      java_jdk: yes

### Debian Buster openjdk
- name: install debian buster openjdk 8 jre
  hosts: debian-buster-openjdk-8-jre
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 8

- name: install debian buster openjdk 8 jdk
  hosts: debian-buster-openjdk-8-jdk
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.java
      java_type: openjdk
      java_version: 8
      java_jdk: yes
