---
- name: install openjdk 6 jdk
  hosts: "*-openjdk-6-jdk"
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 6
      java_type: jdk

- name: install openjdk 7 jdk
  hosts: "*-openjdk-7-jdk"
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 7
      java_type: jdk

- name: install openjdk 8 jdk
  hosts: "*-openjdk-8-jdk"
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 8
      java_type: jdk

- name: install openjdk 9 jdk
  hosts: "*-openjdk-9-jdk"
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: ansible-role-java
      java_version: 9
      java_type: jdk
